/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyAlert: typeof import('@opentiny/vue')['Alert']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyDialogBox: typeof import('@opentiny/vue')['DialogBox']
    TinyFileUpload: typeof import('@opentiny/vue')['FileUpload']
    TinyGrid: typeof import('@opentiny/vue')['Grid']
    TinyGridColumn: typeof import('@opentiny/vue')['GridColumn']
    TinyNavMenu: typeof import('@opentiny/vue')['NavMenu']
    TinyOption: typeof import('@opentiny/vue')['Option']
    TinyPager: typeof import('@opentiny/vue')['Pager']
    TinySearch: typeof import('@opentiny/vue')['Search']
    TinySelect: typeof import('@opentiny/vue')['Select']
    TinySticky: typeof import('@opentiny/vue')['Sticky']
  }
}
